### ISSUE TITLE
Function returns NaN if `{ latitude: 0 }` or `{ longitude: 0 }` is specified

### ISSUE THREAD

**Issue by lzhou-aops** [dcousens/haversine-distance#16]
It looks like https://github.com/dcousens/haversine-distance/issues/13 might not be totally fixed:
```
> const h = require("haversine-distance")
undefined
> h([0,0], [1,1])
157425.537108412
> h({lat:0.0, lon:0.0}, {latitude:1, longitude:1})
157425.537108412
> h({latitude:0.1, longitude:0.1}, {latitude:1, longitude:1})
141682.5877908152
> h({latitude:0.0, longitude:0.0}, {latitude:1, longitude:1})
NaN
```
On version 1.2.1.

**Comment by lzhou-aops** [comment]
Actually, wait, the package.json says I'm on 1.2.1, but the code in node_modules is still using `||` instead of `??`... what's going on

**Comment by dcousens** [comment]
Ah! https://github.com/dcousens/haversine-distance/pull/14 hasn't been released! Oh dear
I'll try and keep this in my inbox to do on Monday :yellow_heart: , otherwise please ping again
