### ISSUE TITLE
Missing `require` export in 1.2.2

### ISSUE THREAD

**Issue by veitbjarsch** [dcousens/haversine-distance#18]
Hi,

when I try to update the plugin it stops working. Digging into the problem showed me that you reference an export.js file in the package.json, which is not available in the bundle:

![image](https://github.com/dcousens/haversine-distance/assets/12811012/d28dedc7-3aa5-485c-be04-cec8823f7f6c)
![image](https://github.com/dcousens/haversine-distance/assets/12811012/43226cf8-74b8-4838-b619-cc3954831d69)

**Comment by superworks-official** [comment]
@dcousens Any update on this?.

**Comment by superworks-official** [comment]
I have one temporary solution for this. 

Remove ^ sign form `haversine-distance:^1.2.1` in package.json file

Use this in package.json file
`haversine-distance:1.2.1` 

And install npm

**Comment by dcousens** [comment]
Should be fixed in https://github.com/dcousens/haversine-distance/commit/b806190259302a0b7c15ee4c0249cbaa57a968d7, released as `v1.2.3`
