### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by sgoertzen** [dcousens/haversine-distance#5]
The latest code changes which include TypeScript definitions are not published to NPM yet.  (https://www.npmjs.com/package/haversine-distance/v/1.1.4)

Could you please push the latest up as 1.1.5?  Thanks!

**Comment by sgoertzen** [comment]
For anyone running into this, the workaround for this is to install from the latest commit.  You can do that with:
`npm install --save dcousens/haversine-distance#18caa412b25239e517e8bc219d4947ebc0e3020d`

**Comment by dcousens** [comment]
Published as `v1.1.5` (sorry for the delay)
