### ISSUE TITLE
TSLint error when used in a typescript (.ts) file

### ISSUE THREAD

**Issue by moseskarunia** [dcousens/haversine-distance#7]
When used in a .ts file, if I use it like:

```
import * as haversineDistance from 'haversine-distance';
// import haversineDistance = require('haversine-distance'); will upset the tslint similarly.

const a = { lat: 32.2084468, lng: 130.4001656 };
const b = { lat: 32.2084468, lng: 130.4001656 };

console.log(haversineDistance(a, b));
```

It will upset the tslint. `haversineDistance(a, b)` is red-underlined, and when I hover it, there's this message:

> This expression is not callable.... [package] has no call signatures.

-----

I submitted PR #6, which will make tslint no longer complain when used in a ts files.

**Comment by dcousens** [comment]
Thanks @moseskarunia - I'll need to test this before I release :+1:

**Comment by moseskarunia** [comment]
Please let me know after you release it to npm. :)
